# Generated by Django 3.2.9 on 2022-04-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Название принтера"),
                ),
                (
                    "api_key",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Ключ доступа к API"
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[("kitchen", "kitchen"), ("client", "client")],
                        max_length=250,
                        verbose_name="Тип чека которые печатает принтер",
                    ),
                ),
                (
                    "point_id",
                    models.CharField(
                        max_length=250, verbose_name="Точка к которой привязан принтер"
                    ),
                ),
            ],
            options={
                "verbose_name": "Принтер",
                "verbose_name_plural": "Принтеры",
            },
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kitchen", "kitchen"), ("client", "client")],
                        max_length=250,
                        verbose_name="Тип чека",
                    ),
                ),
                ("order", models.JSONField(verbose_name="Информация о заказе")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("rendered", "rendered"),
                            ("printed", "printed"),
                        ],
                        default="new",
                        max_length=250,
                        verbose_name="Статус чека",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="pdf/", verbose_name="Ссылка на созданный PDF-файл"
                    ),
                ),
                (
                    "printer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="api.printer",
                        verbose_name="Принтер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чек",
                "verbose_name_plural": "Чеки",
            },
        ),
    ]
